//numkeys
enum
{
  SAT_KEY_1=2,SAT_KEY_2,SAT_KEY_3,SAT_KEY_4,SAT_KEY_5,SAT_KEY_6,SAT_KEY_7,SAT_KEY_8,SAT_KEY_9,SAT_KEY_0
};

//remotekeys
enum
{
  SAT_KEY_TV_RADIO=59,SAT_KEY_RECALL,SAT_KEY_ALT_AUD,SAT_KEY_PHOTO,SAT_KEY_CHECK,SAT_KEY_REPEAT,SAT_KEY_PIP,
  SAT_KEY_UP=103,SAT_KEY_PAGEUP,SAT_KEY_LEFT,SAT_KEY_RIGHT,
  SAT_KEY_DOWN=108,SAT_KEY_PAGEDOWN,
  SAT_KEY_MUTE=113,
  SAT_KEY_POWER=116,
  SAT_KEY_PAUSE=119,
  SAT_KEY_STOP=128,
  SAT_KEY_MENU=139,
  SAT_KEY_FILE=144,
  SAT_KEY_WWW=150,
  SAT_KEY_BACK=158,
  SAT_KEY_RECORD=167,SAT_KEY_REWIND,
  SAT_KEY_VOLUP=187,SAT_KEY_VOLDOWN,SAT_KEY_MULTIFEED,SAT_KEY_PIP_MOVE,SAT_KEY_PIP_SWITCH,SAT_KEY_PIP_CH,SAT_KEY_MUSIC,
  SAT_KEY_PLAY=207,SAT_KEY_FASTFORWARD,
  SAT_KEY_OK=352,
  SAT_KEY_INFO=358,
  SAT_KEY_FAVORITES=364,SAT_KEY_EPG,
  SAT_KEY_SUBTITLE=370,SAT_KEY_TELETEXT,
  SAT_KEY_MP3=391,
  SAT_KEY_RED=398,SAT_KEY_GREEN,SAT_KEY_YELLOW,SAT_KEY_BLUE,
  SAT_KEY_SLOW=409
};

//frontpanel keys
enum
{
  SAT_KEY_FRONT_UP=66,SAT_KEY_FRONT_DOWN,SAT_KEY_FRONT_LEFT,
  SAT_KEY_FRONT_RIGHT=87,SAT_KEY_FRONT_OK,
  SAT_KEY_FRONT_BACK=183,SAT_KEY_FRONT_MENU,SAT_KEY_FRONT_FILE,SAT_KEY_FRONT_POWER
};

